repository: tumble1999/ctf-donate 

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  - ".gitignore"
  - CNAME
  - icomoon-selection.json
